services:
    postgres:
        image: 'postgres:latest'
        environment:
            - 'POSTGRES_DB=tayduongdb'
            - 'POSTGRES_PASSWORD=secret'
            - 'POSTGRES_USER=user'
        ports:
            - '5431:5432'

    #    app:
    #        build:
    #            context: .
    #            dockerfile: Dockerfile
    #        restart: always
    #        ports:
    #            - '8080:8080'
    #        depends_on:
    #            - postgres
    #        environment:
    #            - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tayduongdb'
    #            - 'SPRING_DATASOURCE_USERNAME=user'
    #            - 'SPRING_DATASOURCE_PASSWORD=secret'

    redis:
        image: 'redis:latest'
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning


    kafka:
        image: 'bitnami/kafka:latest'
        #        networks:
        #            - app-tier
        ports:
            - '9092:9092'
        environment:
            - KAFKA_CFG_NODE_ID=0
            - KAFKA_CFG_PROCESS_ROLES=controller,broker
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        volumes:
            - ./kafka1:/bitnami/kafka
