services:
    postgres:
        image: 'postgres:latest'
        environment:
            - 'POSTGRES_DB=tayduongdb'
            - 'POSTGRES_PASSWORD=secret'
            - 'POSTGRES_USER=user'
        ports:
            - '5431:5432'
