DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS images;

CREATE TABLE account
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account     VARCHAR(255),
    email       VARCHAR(255),
    password    VARCHAR(255),
    status      SMALLINT                                 NOT NULL,
    employee_id INTEGER                                  NOT NULL,
    CONSTRAINT pk_account PRIMARY KEY (id)
);

CREATE TABLE employee
(
    employee_id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name      VARCHAR(255),
    last_name       VARCHAR(255),
    gender          SMALLINT,
    date_of_birth   DATE,
    phone           VARCHAR(20),
    address         VARCHAR(255)                             NOT NULL,
    department_name VARCHAR(255),
    remark          VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_employee PRIMARY KEY (employee_id)
);

ALTER TABLE account
    ADD CONSTRAINT uc_account_account UNIQUE (account);

ALTER TABLE account
    ADD CONSTRAINT uc_account_email UNIQUE (email);

ALTER TABLE account
    ADD CONSTRAINT uc_account_employee UNIQUE (employee_id);

ALTER TABLE account
    ADD CONSTRAINT FK_ACCOUNT_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (employee_id);


CREATE TABLE images
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name   VARCHAR(255),
    file_url    VARCHAR(255),
    user_id     VARCHAR(255),
    upload_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_images PRIMARY KEY (id)
);

ALTER TABLE account
    ADD role VARCHAR(255) DEFAULT 'USER';