DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS images;
DROP TABLE IF EXISTS chi_tiet_don_hang;
DROP TABLE IF EXISTS don_hang;
DROP TABLE IF EXISTS khach_hang;
DROP TABLE IF EXISTS san_pham;

CREATE TABLE account
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account     VARCHAR(255),
    email       VARCHAR(255),
    password    VARCHAR(255),
    status      SMALLINT                                 NOT NULL,
    employee_id INTEGER                                  NOT NULL,
    CONSTRAINT pk_account PRIMARY KEY (id)
);

CREATE TABLE employee
(
    employee_id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name      VARCHAR(255),
    last_name       VARCHAR(255),
    gender          SMALLINT,
    date_of_birth   DATE,
    phone           VARCHAR(20),
    address         VARCHAR(255)                             NOT NULL,
    department_name VARCHAR(255),
    remark          VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_employee PRIMARY KEY (employee_id)
);

ALTER TABLE account
    ADD CONSTRAINT uc_account_account UNIQUE (account);

ALTER TABLE account
    ADD CONSTRAINT uc_account_email UNIQUE (email);

ALTER TABLE account
    ADD CONSTRAINT uc_account_employee UNIQUE (employee_id);

ALTER TABLE account
    ADD CONSTRAINT FK_ACCOUNT_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (employee_id);


CREATE TABLE images
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name   VARCHAR(255),
    file_url    VARCHAR(255),
    user_id     VARCHAR(255),
    upload_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_images PRIMARY KEY (id)
);

ALTER TABLE account
    ADD role VARCHAR(255) DEFAULT 'USER';



-- Tạo extension để sử dụng UUID nếu chưa có
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Bảng khách hàng
CREATE TABLE khach_hang (
                            id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                            ma_khach_hang TEXT,
                            ten_khach_hang TEXT,
                            dia_chi TEXT,
                            nhom_kh_ncc TEXT,
                            ma_so_thue TEXT,
                            dien_thoai TEXT,
                            ngung_theo_doi BOOLEAN
);

-- Bảng sản phẩm
CREATE TABLE san_pham (
                          id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                          ma_san_pham TEXT,
                          ten_san_pham TEXT,
                          don_vi TEXT,
                          don_gia DECIMAL(18, 2)
);

-- Bảng đơn hàng
CREATE TABLE don_hang (
                          id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                          ma_don_hang TEXT,
                          ma_khach_hang UUID REFERENCES khach_hang(id),
                          ngay_dat DATE,
                          ngay_thanh_toan DATE,
                          dieu_khoan_tt TEXT,
                          tong_tien DECIMAL(18, 2),
                          tien_vat DECIMAL(18, 2),
                          tong_thanh_toan DECIMAL(18, 2)
);

-- Bảng chi tiết đơn hàng
CREATE TABLE chi_tiet_don_hang (
                                   id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                                   ma_don_hang UUID REFERENCES don_hang(id),
                                   ma_san_pham UUID REFERENCES san_pham(id),
                                   so_luong INT,
                                   thanh_tien DECIMAL(18, 2)
);

